Clean up the Nix flake, recommended practices, provide overlay
daylinmorgan/monolisa-nerdfont-patch pull request #6
Opened 2024-02-02 07:18 UTC by spikespaz

This is how I organize my Nix flakes and allow for the utmost compatibility for any desired use-case. When I say "recommended practices", they are my own, but also very similar to the "best practices" purported by the community.

I recommend reviewing each commit individually.

2024-02-02 20:39 UTC, daylinmorgan commented
> I recommend reviewing each commit individually.

Some of these changes aren't really independent, but I'll try.

Here are some high-level thoughts:

These changes broke `nix flake check` and `nix flake show`

```sh
❯ nix flake check
error:
       … while checking flake output 'overlays'

         at /nix/store/pps7hwqysf2l449krqg70yx3z2gslhbj-source/flake.nix:20:7:

           19|     in {
           20|       overlays = {
             |       ^
           21|         default = pkgs: pkgs0: {

       … while checking the overlay 'overlays.default'

         at /nix/store/pps7hwqysf2l449krqg70yx3z2gslhbj-source/flake.nix:21:9:

           20|       overlays = {
           21|         default = pkgs: pkgs0: {
             |         ^
           22|           monolisa-nerdfont-patch = pkgs.stdenv.mkDerivation {

       error: overlay does not take an argument named 'final'
❯ nix flake show
git+file:///home/daylin/stuff/fonts/monolisa-nerdfont-patch?ref=refs/heads/spikespaz/main&rev=fa54af9cba60c7ff2e2928a5dbe95800f4bc57dd
├───devShells
│   ├───aarch64-linux
│   │   └───default omitted (use '--all-systems' to show)
│   └───x86_64-linux
│       └───default: development environment 'nix-shell'
├───formatter
│   ├───aarch64-linux omitted (use '--all-systems' to show)
error:
       … while evaluating the attribute 'packages.x86_64-linux.default'

         at /nix/store/96dn6crb2c2l9mwv64a0yq7rnwbf9v6h-source/flake.nix:73:11:

           72|         packages = rec {
           73|           default = nixfmt;
             |           ^
           74|           nixfmt = pkgs.haskellPackages.nixfmt;

       … while evaluating the attribute 'haskellPackages.nixfmt'

         at /nix/store/96dn6crb2c2l9mwv64a0yq7rnwbf9v6h-source/flake.nix:31:15:

           30|             packageOverrides = self: super: {
           31|               nixfmt = self.callCabal2nix "nixfmt" src { };
             |               ^
           32|             };

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: cannot build '/nix/store/qqkh6wvkk8y3ansvbcxxq2ysgdnh07dy-cabal2nix-nixfmt.drv^out' during evaluation because the option 'allow-import-from-derivation' is disabled
```

With regards to adding `nixfmt`. Seems unnecessary to me to add a formatter for a single (< 100LOC) `.nix` file that probably won't even change much after this (until nix breaks something).  But, also as a flake input it adds **OVER** 60 additional inputs for little benefit! (FWIW I usually use alejandra).

Using `nix-systems` is fine with me, but the community consensus seems quite unsettled on that being the appropriate solution to a perceived problem with defining outputs.

2024-02-02 20:39 UTC, daylinmorgan approved these changes

2024-02-02 20:43 UTC, daylinmorgan requested changes
I'd prefer to keep a `forAllSystems` function that that takes `pkgs` something like:
Removing the formatter output removes the standalone use for the `eachSystem` function and then negates the redundant `let pkgs = pkgsFor.${system}` everywhere else.

```nix
     forAllSystems = f:
      genAttrs (import systems)
       (system:
          f (import nixpkgs {
            localSystem.system = system;
            overlays = [ self.overlays.default ];
          }));
```

2024-02-02 20:43 UTC, daylinmorgan approved these changes

2024-02-10 19:10 UTC, spikespaz commented
The problem with Alejandra is that it causes very noisy diffs, which is a main I contend with every time I rebase a PR.

2024-02-10 19:23 UTC, spikespaz commented
Take [this one](https://github.com/daylinmorgan/monolisa-nerdfont-patch/pull/6/commits/956a66852bef80dcc221bd61df95857ab537e490) for example. It messes with indentation so much. I really don't like Alejandra.

2024-02-10 19:25 UTC, spikespaz commented
And [this one](https://github.com/daylinmorgan/monolisa-nerdfont-patch/pull/6/commits/f7b361c48c77734e69565714ba6042ac99189ce9), the diff was much nicer before.

2024-02-10 19:27 UTC, spikespaz commented
> Some of these changes aren't really independent, but I'll try.

The commits are as they are because I have experience with people telling me no to Nixfmt, and this makes the rebase easier when I inevitably replace it with Alejandra. :)

2024-02-10 19:35 UTC, spikespaz commented
If you don't already know, Alejandra makes [manual merges painful](https://github.com/daylinmorgan/monolisa-nerdfont-patch/files/14230297/flake.nix.txt).

2024-02-10 19:44 UTC, spikespaz commented
That should be all the changes you asked for done.

2024-02-10 20:36 UTC, merged

2024-02-10 20:36 UTC, daylinmorgan commented
Thanks!

2024-03-27 13:31 UTC, spikespaz commented on flake.nix
> +          nativeBuildInputs = with pkgs; [makeWrapper];
I just noticed, this change is bad, don't *ever* use an external `pkgs` from inside an overlay. You should treat `final` as if it were `pkgs`, otherwise you evaluate Nixpkgs stages twice. See [here](https://github.com/hyprwm/Hyprland/pull/4558#issuecomment-1931125401) for some relevant discussion.

2024-03-27 13:38 UTC, spikespaz commented on flake.nix
>    };
If you don't want the formatter as an input, I understand; use it from Nixpkgs instead. Please use the flake's formatter output so that a manual `nix fmt` command works. That is the intended purpose of `formatter`, it is special. I, personally, extend this functionality and have my editor run `nix fmt` on every file save. This allows me to type long lines and periodically re-format to keep my head clear and the code clean as I work on it.

2024-03-27 13:41 UTC, spikespaz commented on flake.nix
> +              --set PATH ${makeBinPath (with final; [fontforge])}
This is subjective, and I understand that it is preference, but parts of Nixpkgs are moving away from this, which is why I changed it. The idea is to keep it clear what is in `lib` and what is in the prelude. You may safely ignore this comment, especially since I can't find the relevant discussion that I read and I can provide no evidence other than anecdotal.

2024-03-27 13:45 UTC, spikespaz commented on flake.nix
> +          nativeBuildInputs = with pkgs; [makeWrapper];
Never mind the above comment. I now see line 26. If this is your preference (and you should be consistent with your change on lines 16-22) consider using the [naming scheme](https://github.com/hyprwm/Hyprland/pull/4558#issuecomment-1914783475) that I have come up with in the thread I have already linked. It does make sense to rename `final` to `pkgs`, but as `final`/`self` and `prev`/`super` can also be used for `overrideAttrs` (and others) inside overlays, to avoid shadowing, consider `pkgs: pkgs0`.

2024-03-27 13:58 UTC, spikespaz commented on flake.nix
>    };
I have deleted my original comment here as it is in the wrong place.

The comment I intended for here is a question, not a suggestion or correction: why did you choose to use `buildInputs` over `packages`?

Now a little pushy: the function `mkShell` is a [smart function](https://github.com/NixOS/nixpkgs/blob/529a53c13fe7b403fd81da362197f561d1ca6bbe/pkgs/build-support/mkshell/default.nix#L19-L22), is documented, and it does not suggest using `buildInputs` (though this is common practice). See [the manual](https://github.com/NixOS/nixpkgs/blob/e21a8a42932d10970574002882041bbf6c14ca59/doc/build-helpers/special/mkshell.section.md?plain=1#L26-L27).

2024-03-27 14:02 UTC, spikespaz commented on flake.nix
> +              --set PATH ${makeBinPath (with final; [fontforge])}
Perhaps the issue I am thinking of in Nixpkgs is the over-usage of `with` which causes name-clashing. I don't remember well.

2024-03-27 14:16 UTC, spikespaz commented on flake.nix
> -    formatter = eachSystem (system: _: alejandra.packages.${system}.default);
I understand not wanting to take the formatter's flake as an input, however consider re-introducing the formatter output because it is special. You can use the package from Nixpkgs instead. It allows nix fmt to work. This is useful: I manually run nix fmt to keep myself organized while I am working on dirty code, and additionally, configure my editor to format the code using the nix fmt command when the file is saved. This allows me to write long lines, and then semi-automatically format to keep my head clear and the code readable.

2024-03-27 14:22 UTC, spikespaz commented on flake.nix
>    };
I understand not wanting to take the formatter's flake as an input, however consider re-introducing the `formatter` output because it is special. You can use the package from Nixpkgs instead. The output allows `nix fmt` to work. This is useful: I manually run `nix fmt` to keep myself organized while I am working on dirty code, and additionally, configure my editor to format the code using the `nix fmt` command when the file is saved. This allows me to write long lines, and then semi-automatically format to keep my head clear and the code readable.

2024-03-27 14:31 UTC, spikespaz commented
I have added comments, as I am sure your inbox is well-aware. I probably spammed you while struggling with the GitHub UI. It seemed to post them in the wrong locations, and when I went to correct them, refreshing the page showed that I had double-posted, edited, or even had it correct in the first place. I have absolutely no idea what was happening; I do sincerely apologize.

2024-03-31 16:11 UTC, daylinmorgan commented on flake.nix
> +        buildInputs = with pkgs; [fontforge python3 pre-commit];
It make no difference they are all just merged.

2024-03-31 16:13 UTC, daylinmorgan commented on flake.nix
>    };
I am well aware of how `nix fmt` works.

2024-03-31 19:24 UTC, spikespaz commented on flake.nix
> +          nativeBuildInputs = with pkgs; [makeWrapper];
No, `nixfmt` caused the check failure. Not this.